
---
- hosts: all
  become: true
  tasks:

  - name: install apache2amd php packages in Ubuntu
    package:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes
